### PR TITLE
Use the black Formatting Tool on this Project

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR is the result of using the [`black`](https://github.com/psf/black) formatting tool on this code base. Each directory is broken up into its own commit to make it easier to track the changes.

## 💭 Motivation and Context ##

All of our current Python projects use the `black` formatter as part of our `pre-commit` hooks to maintain consistent formatting in our Python code. This project should be no different, so it must be dragged into the darkness.

## 🧪 Testing ##
 None. Since this is just PEP8 compliant formatting, this should have no difference on functionality.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Color our world blackened.
Blackened!

**Review by dav3r — APPROVED** [review]
What could possibly go wrong? 🏭

**Review by hillaryj — APPROVED** [review]
It would be nice to test this...

Did it complain at all about using `.format()` in logging statements, like in `extras/data-pusher/data-pusher.py`?

🖤

**Comment by mcdonnnj** [comment]
> 
> 
> It would be nice to test this...
> 
> Did it complain at all about using `.format()` in logging statements, like in `extras/data-pusher/data-pusher.py`?
> 
> 🖤

[black](https://github.com/psf/black) only performs [PEP8](https://www.python.org/dev/peps/pep-0008/) compliant code formatting. The only linting it does is fail if it cannot parse the source code in the file.

None of our current `pre-commit` hooks complain about using `.format()` in calls to `logging`. I saw that when I was testing `pylint` as a `pre-commit` hook to add, and it led me to investigate why. It is currently a non-automated "best practice" for us, but I'd like to iron out a `pylint` configuration file we'd all be happy with to integrate it into our `pre-commit` hook selection.

**Comment by mcdonnnj** [comment]
> 
> 
> It would be nice to test this...
> 
> Did it complain at all about using `.format()` in logging statements, like in `extras/data-pusher/data-pusher.py`?
> 
> 🖤

I deployed these changes to my testing environment and did verify that functionality works as expected.

**Pull request merged**
