### PR TITLE
Add Package Dependency and Pin to Avoid Version that Breaks on Python 2

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR adds a dependency for [python-engineio](https://github.com/miguelgrinberg/python-engineio) with a version pin.

## 💭 Motivation and Context ##

The `python-engineio` package is a dependency of [python-socketio](https://github.com/miguelgrinberg/python-socketio), which is itself a dependency of [Flask-SocketIO](https://github.com/miguelgrinberg/Flask-SocketIO), and `Flask-SocketIO` is a requirement for this project.

I noticed a problem with the dashboard in my testing environment from the following Python 3 only code:

```python
from json import JSONDecodeError
```

Upon investigation I saw that this was added in `v3.14`. Someone else created an issue (https://github.com/miguelgrinberg/python-engineio/issues/206), and based on the developer's response we should expect no support for Python 2.

## 🧪 Testing ##

I deployed this in my testing environment and verified that the dashboard worked as expected with the correct version of `python-engineio` installed.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Gotta pin 'em all!

**Comment by jsf9k** [comment]
This PR needs to be merged to continue the CyHy update for this month.  Unfortunately @mcdonnnj and I are the only mice stirring on this New Year's Eve Eve, so we have to go ahead and merge with only a single review.

"You adapt. You overcome. You improvise.”  -- Clint Eastwood in "Heartbreak Ridge"

**Comment by mcdonnnj** [comment]
I will enable two required reviews once this has merged.

**Comment by mcdonnnj** [comment]
There were actually no branch protections in place. I have created our usual branch protection rules for the `develop` branch.

**Pull request merged**
