### PR TITLE
Update numpy and pandas versions to match those in cisagov/cyhy-reports

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request pins the versions of the Python packages `numpy` and `pandas` to match the versions pinned in [cisagov/cyhy-reports](https://github.com/cisagov/cyhy-reports).

## 💭 Motivation and context ##

Since this repo is a dependency of [cisagov/cyhy-reports](https://github.com/cisagov/cyhy-reports), and the versions of the `numpy` and `pandas` Python packages are pinned there, the versions must also be pinned here.  If not, then [cisagov/cyhy-reports](https://github.com/cisagov/cyhy-reports) installs one version of these Python packages, [cisagov/ncats-webd](https://github.com/cisagov/ncats-webd) installs another, and therefore [cisagov/ansible-role-cyhy-reports](https://github.com/cisagov/ansible-role-cyhy-reports) cannot be not idempotent.  More importantly, the version of these Python packages that actually gets installed via [cisagov/ansible-role-cyhy-reports](https://github.com/cisagov/ansible-role-cyhy-reports) is undetermined.

## 🧪 Testing ##

@mcdonnnj has successfully built a new CyHy dashboard AMI with these changes and successfully tested it in his CyHy testing environment.

Update from @mcdonnnj:
I have seen no issues in testing and I have heard of no issues with these changes deployed.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by dav3r** [comment]
The version pinning looks fine to me.  As discussed in chat earlier, I agree with @mcdonnnj that this should be tested in a fresh dashboard AMI.  Once that testing has been successfully completed, I'll approve this PR.

**Comment by jsf9k** [comment]
@mcdonnnj, any updates on your testing?

**Comment by mcdonnnj** [comment]
> @mcdonnnj, any updates on your testing?

@jsf9k I have updated the description to mention that no issues have been seen.

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Review by dav3r — APPROVED** [review]
📌 👍

**Pull request merged**
